apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-31T00:50:37Z"
  generateName: coredns-5dd5756b68-
  labels:
    k8s-app: kube-dns
    pod-template-hash: 5dd5756b68
  name: coredns-5dd5756b68-bmrp2
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-5dd5756b68
    uid: 898b3e3a-0e9a-4a59-8203-cfafc767e8ae
  resourceVersion: "2175"
  uid: 1a0cf18e-5360-4933-842a-211f0074562c
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - kube-dns
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: registry.k8s.io/coredns/coredns:v1.10.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: coredns
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 9153
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8181
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - all
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wvgpf
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: docker-desktop
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: coredns
    name: config-volume
  - name: kube-api-access-wvgpf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T00:50:37Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T17:46:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T17:46:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T00:50:37Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://8b42f4e3490c494b5613267c548bab3fd10bd588507e9a694738dea9ee541d0a
    image: registry.k8s.io/coredns/coredns:v1.10.1
    imageID: docker://sha256:ead0a4a53df89fd173874b46093b6e62d8c72967bbf606d672c9e8c9b601a4fc
    lastState:
      terminated:
        containerID: docker://03d9a117010fcee47c27ac2d1f7e3c8093d0e8006486c9949ddefe310c00b888
        exitCode: 0
        finishedAt: "2024-01-31T17:45:35Z"
        reason: Completed
        startedAt: "2024-01-31T00:59:45Z"
    name: coredns
    ready: true
    restartCount: 2
    started: true
    state:
      running:
        startedAt: "2024-01-31T17:46:24Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.11
  podIPs:
  - ip: 10.1.0.11
  qosClass: Burstable
  startTime: "2024-01-31T00:50:37Z"
