name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t raydium/boston_housing:latest --push .
        
    - name: Set up kubectl
      run: |
          echo "${{ secrets.KUBE_CONFIG_BASE64 }}" | base64 --decode > kubeconfig2.yaml
          kubectl config get-contexts --kubeconfig=kubeconfig2.yaml
          cat kubeconfig2.yaml
          export KUBECONFIG=$PWD/kubeconfig2.yaml
          
      env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG_BASE64 }}

    - name: Deploy to Kubernetes
      run: |
        kubectl config current-context
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG_BASE64 }}
